// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUcqGFXk9_JdGA-GNLj5tISnLZW_6JqGA',
    appId: '1:744302204979:web:eb1604fbb47dea4d73eb46',
    messagingSenderId: '744302204979',
    projectId: 'docfinder-6c361',
    authDomain: 'docfinder-6c361.firebaseapp.com',
    storageBucket: 'docfinder-6c361.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBErPiWBLhBhVnb6bzj9D6cAXfkCVbiO84',
    appId: '1:744302204979:android:85008e2926d7bd0173eb46',
    messagingSenderId: '744302204979',
    projectId: 'docfinder-6c361',
    storageBucket: 'docfinder-6c361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCASFmxmN9xVy6b8ws5cCC4fEHrkGgNjck',
    appId: '1:744302204979:ios:7d244b2cc82b951773eb46',
    messagingSenderId: '744302204979',
    projectId: 'docfinder-6c361',
    storageBucket: 'docfinder-6c361.firebasestorage.app',
    iosBundleId: 'com.docfinder.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCASFmxmN9xVy6b8ws5cCC4fEHrkGgNjck',
    appId: '1:744302204979:ios:7d244b2cc82b951773eb46',
    messagingSenderId: '744302204979',
    projectId: 'docfinder-6c361',
    storageBucket: 'docfinder-6c361.firebasestorage.app',
    iosBundleId: 'com.docfinder.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUcqGFXk9_JdGA-GNLj5tISnLZW_6JqGA',
    appId: '1:744302204979:web:a30562a5a32b819f73eb46',
    messagingSenderId: '744302204979',
    projectId: 'docfinder-6c361',
    authDomain: 'docfinder-6c361.firebaseapp.com',
    storageBucket: 'docfinder-6c361.firebasestorage.app',
  );
}
